### ISSUE TITLE
Can't download song from Youtube

### ISSUE THREAD

**Issue by montassar00** [AllToMP3/alltomp3-app#101]
when i try do download some songs from youtube it stuck at this !!!
screenshot : https://imgur.com/a/V47HzU4

**Comment by pranjal815** [comment]
I am also facing the same issue. When i try to download the song from youtube then the song is not getting saved. The progress bar shows that it is downloaded 100% but I believe it is not.

**Comment by SamuelMezger** [comment]
I'm having a similar problem. I tried to download a YouTube playlist but only 6 out of 40 songs got saved. Running it through the terminal these are the error messages:
```
[AT3] event error Error: Error: Error: Error: status code 403
    at EventEmitter.dl.once (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:1051:35)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at EventEmitter.dl.once (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:459:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Readable.download.once (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:305:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
    at Request.response (/opt/AllToMP3/resources/app/node_modules/youtube-dl/lib/youtube-dl.js:74:27)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/opt/AllToMP3/resources/app/node_modules/youtube-dl/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
[AT3] event download-end undefined
Error: ffmpeg exited with code 1: /tmp/R9XjG8XM6X.mp3.video: No such file or directory
    at ChildProcess.<anonymous> (/opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
