### ISSUE TITLE
Seems not to work for Spotify Playlist at all

### ISSUE THREAD

**Issue by zoqqa** [AllToMP3/alltomp3-app#104]
Hello @NTag ,
thank you for your tool which seems to be very nice. All I want is a GUI tool for my parents so they can download their spotify playlist easily.

I'm trying to use your tool but getting involved with a freeze. I hope to get your support.

* My operating system is: Windows 7, 64bit;
* My AllToMP3 version is: 0.3.8.124;
* My Spotify version is actual and freemium, but not using it on these OS.

My steps to download:
- Download and Install AllToMP3 in user context (No Admin).
- Paste path from Spotify Playlist
- Press ENTER

AllToMP3 begins to download 4 files in background to the TEMP directory.
![grafik](https://user-images.githubusercontent.com/48674455/54521628-987a7000-496b-11e9-9168-cab9c501fd82.png)

After 4 songs with cryptic names nothings happens and the tool seems to freeze:

![grafik](https://user-images.githubusercontent.com/48674455/54521376-18540a80-496b-11e9-8db2-654b3c171f6b.png)

The Logs directory (AppData\Roaming\AllToMP3\logs) is empty.
The standard destination directory (saving-path) is empty: 
![grafik](https://user-images.githubusercontent.com/48674455/54521860-20607a00-496c-11e9-8ab3-a64b62dca7b0.png)

I've tried it moretimes, nothing changes.
I've tried it without firewall and without AV but nothing changes.

Do I have to run spotify on my OS?
Do I have to get premium Version of spotify instead of freemium?

Thank you very much for your support 🙏

**Comment by JacopoMarcheselli** [comment]
Same here!
With some album or playlist I manage to make it work, but others are totally impervious to download.
It downloads the first four and then never completes them.
Even trying song by song they appear as completed on the program but are nowere to be found in the target folder.

Thank you anyway for this amazing project!

**Comment by ens-pstasz** [comment]
I have run "alltomp3 --help" and this made lot of logs out on console.
This is probably the issue (indeed the JPG file is locked by app):
(node:708) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reject
ion id: 3): Error: EPERM: operation not permitted, rename 'C:\Users\x\AppD
ata\Local\Temp\1DVqscFIj8.mp3.cover.resized.jpg' -> 'C:\Users\x\AppData\Lo
cal\Temp\1DVqscFIj8.mp3.cover.jpg'
Maybe someone knows what does resize?

**Comment by blissland** [comment]
I submitted a fix for this problem at the end of January:

https://github.com/AllToMP3/alltomp3/pull/23

However the current release (0.3.8) was created on 20th January and so does not contain the fix.

**Comment by FrozenBeard** [comment]
EXACTLY the same here on Mac, makes it completely pointless app.

**Comment by NTag** [comment]
Can you try with the latest update, 0.3.9?

**Comment by pedro2d10** [comment]
For me, the updated version seem's to work well with playlist. Befor, it only download 11 traks on 41.

**Comment by ens-pstasz** [comment]
Doesn't work for me. On spotify list gives:
[AT3] event download-end 4
Error: ffmpeg exited with code 1: C:\Users\x\AppData\Local\Temp\Ow8dC7H8LC
.mp3.video: Invalid data found when processing input
    at ChildProcess.<anonymous> (C:\Users\x\AppData\Local\Programs\AllToMP
3\resources\app.asar\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
on all 4 threads.

**Comment by bramgcohen** [comment]
Same on Mac 0.3.10 . Debug shows:
`[AT3] event download-end 7
Error: ffmpeg exited with code 1: /var/folders/4w/vx3vqhlj0wv7rkd20zg2n2tm0000gn/T//vPSbrqxjRp.mp3.video: Invalid data found when processing input

    at ChildProcess.<anonymous> (/Applications/AllToMP3.app/Contents/Resources/app.asar/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`
