### ISSUE TITLE
Can not download spotify playlists

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [AllToMP3/alltomp3-app#114]
i'm a debian 9 user with 0.3.10 of alltomp3 app & i can not download all songs from (https://open.spotify.com/user/edsheeran/playlist/0uFhZpiffd4h8fcBgw42i1?si=TbLc__v3RsqYUPYax3S1lw) & i tried to get like a log (so i ran `alltomp3` at my cmd) & got this:

```Error: ffmpeg exited with code 1: /tmp/g1FsjYMAtu.mp3.video: Invalid data found when processing input

    at ChildProcess.<anonymous> (/opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)```
**NOTE**: its happen with all pluralists not just this, its like limit or something

**Comment by cryptolute** [comment]
Windows user 0.3.1.0 here, playlist or any single songs wont download, just has a progress bar that gets frozen and never downloads

https://open.spotify.com/album/527IcFU7CsvI0w7gLIwJM2

**Comment by satnapar** [comment]
Mac user 0.3.10 here, reporting the same....
https://open.spotify.com/user/whenwedip/playlist/0vg01XrTn6sQZErvZIzdEO?si=p1FMeCxFT7ufk8t1hwYB-A

**Comment by slartibarfast1989** [comment]
Same issue here on Windows 10. The playlist gets resolved for all the song names on the playlist, it then just hangs with nothing downloading.

**Comment by g8f6r4e7x2** [comment]
Same on Windows 10 version 0.3.8
it's able to show the list of songs but download just wont start

**Comment by tonisilvan** [comment]
same here

**Comment by alvaro-canepa** [comment]
Same problem. Linux Mint 19.1 Tessa.

[pastebin log](https://pastebin.com/0kiEHZGf)
