### ISSUE TITLE
Stops half way

### ISSUE THREAD

**Issue by 19203kkd** [AllToMP3/alltomp3-app#123]
when i dowload my songs on alltomp3 it stops half way and stops working.

**Comment by Petersoj** [comment]
This also is happening to me. I'm downloading a song from YouTube and the following error is outputted (MacOS with latest AllToMP3 version):
```
Error: ffmpeg exited with code 1: /var/folders/mq/bp83ty155591hlyvw92kngrm0000gn/T//PEwk2kLpjx.mp3.video: Invalid data found when processing input

    at ChildProcess.<anonymous> (/Applications/AllToMP3.app/Contents/Resources/app.asar/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
The album art, album name, artist name, and song name are properly fetched and rendered, but the progress bar around the album art stops halfway.

**Comment by Petersoj** [comment]
It's only happening on certain videos such as this one: https://www.youtube.com/watch?v=QuoxgEomtc0

**Comment by adyanth** [comment]
Mine stops halfway for spotify songs. 

Is there any way to extract album/artist information only, rather than download the song when it fails?

**Comment by luluwebmaster** [comment]
Hello,

I have the same problem, do you have a solution ?

Exemple of video : https://www.youtube.com/watch?v=4I72JZ6No1o

Thank you !

**Comment by amzaf** [comment]
Same issue here. Please check out this log:

`[AT3] suggestions https://open.spotify.com/track/52CLfFCVF5GWdzFvHknY6l
[AT3] downloadTrackURL { folder: '/Users/username/Music',
  id: 'qvbvXmA0Zm',
  url: 'https://open.spotify.com/track/52CLfFCVF5GWdzFvHknY6l' }
WARNING: Unable to extract video title

[AT3] event download { progress: '39.13' }
[AT3] event download { progress: '78.26' }
[AT3] event download { progress: '100.00' }
[AT3] event download-end undefined
Error: ffmpeg exited with code 1: /var/folders/y7/tm7968x97cvg9vvpnzrt9s1m0000gn/T//8EwJ7xLhRN.mp3.video: Invalid data found when processing input

    at ChildProcess.<anonymous> (/Applications/AllToMP3.app/Contents/Resources/app.asar/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

**Comment by amzaf** [comment]
I guess I know what happens. I tried to manually download the url in the log I posted earlier. Spotify returns a webpage instead. I guess it may be related to user logins and authorization.

**Comment by Faeb35** [comment]
I also had the issue, that AlltoMP3 was not able to download some certain songs from Spotify. For instance some single songs of an album got not downloaded. I tested on two computers with the same result. Now I replaces the ffmpeg.exe and ffplay.exe with the newest version from (4.2.1), this seams to resolve the issue for me. Before there was version 3.2.2. You finde ffmpeg.exe here:
%userdata%\AppData\Local\Programs\AllToMP3\resources\app.asar.unpacked\bin

**Comment by amzaf** [comment]
This project looks like it is abandoned. I'd suggest anyone having issues take a look at https://github.com/ritiek/spotify-downloader

**Comment by JeroenBos** [comment]
I'm pretty sure this has the same cause as described [here](https://github.com/AllToMP3/alltomp3-app/issues/139#issuecomment-565715158).

**Comment by adyanth** [comment]
The issue you point to seems to be for multiple downloads from a playlist, but the error might be the same.

**Comment by Faeb35** [comment]
Hi Guys,
There's a simple reason why some songs are not downloading:
This app is not really downloading from Spotify!! It just seams to takes the information from Spotify and try to download it from somewhere else (YouTube?). 
So, if a song is not available somehwere else then on Spotify it can't be downloaded. What's even more terrible (there some other issues open here on Github for that): For me it very often just downloaded another song instead the one I wanted and labeled it like what I wanted.
If you're looking for a true spotify-ripper, try this:
https://github.com/hbashton/spotify-ripper

**Comment by adyanth** [comment]
That I know. The song downloads to temp but does not rename and add ID3 tags. Sometimes all of those are downloaded, but not combined and moved to the Music folder.

**Comment by moosty-tr** [comment]
After pc raises out of memory error,  AllToMp3 continues to download several more songs,  then shuts down. 

When I restart the application it does not remember previous list and if I give the same list again, it starts from the beginnig and re-downloading same songs.

It should be very nice to have a resume capability on AllToMp3 application.
