### ISSUE TITLE
Download not working on ubuntu

### ISSUE THREAD

**Issue by gianniocchipinti** [AllToMP3/alltomp3-app#130]
Hi. when i download a playlist i get this error 
[AT3] event convert 26
[AT3] event convert-end 26
[AT3] event infos 26
[AT3] event end-url 26
[AT3] event begin-url 28
WARNING: Unable to extract video title

[AT3] event download 28
[AT3] event download 28
[AT3] event download-end 28
Error: ffmpeg exited with code 1: /tmp/K1TobCOK7U.mp3.video: Invalid data found when processing input

    at ChildProcess.<anonymous> (/opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

I use ubuntu mate

**Comment by JeroenBos** [comment]
I'm pretty sure this has the same cause as described [here](https://github.com/AllToMP3/alltomp3-app/issues/139#issuecomment-565715158).
