### ISSUE TITLE
alltomp3 wont download songs anymore

### ISSUE THREAD

**Issue by akoralage** [AllToMP3/alltomp3-app#148]
i ve tried youtube, spotify and even changed the youtube.dl file but it wont work
![image](https://user-images.githubusercontent.com/60186335/72904595-27f36b00-3d55-11ea-8470-66acdd2d3959.png)

**Comment by Crazychemist2** [comment]
Yup. It's not working, and it's been like this for a couple days now. Hope it gets fixed soon, my download playlist is getting bigger!

**Comment by Darthmonkey** [comment]
It's always been a little hit and miss, but I can't get anything to download now.

**Comment by tomquental** [comment]
Writing on this as well in case someone knows a solution I don't!

I've had the same spotify playlist download issue reported in [Stuck downloading Spotify Playlist #139](https://github.com/AllToMP3/alltomp3-app/issues/139). I'd like to check if anybody has the same problem (on Windows 10, alltomp3 version 0.3.11.128) as me still! All the threads pertaining to this issue seem to be dead by now.

**Comment by Codingboy65** [comment]
@tomquental I use windows 10 that is on the latest build and I am no longer able to download music from a Spotify playlist, it will download 1 song and stop.
![Annotation 2020-01-30 220119](https://user-images.githubusercontent.com/33443001/73516023-1d1b8480-43ac-11ea-92fd-75d28d32ccff.jpg)

**Comment by ReachForTheDead** [comment]
There is an "downloading update" icon showing top right, but it has been stuck for a while. Thought it was a bug and tried downloading multiple songs, but it keeps not working. Guess I'll have to wait! 
![image](https://user-images.githubusercontent.com/49784166/73867332-cfd56200-4846-11ea-83dc-f92033132c8e.png)

**Comment by MrGKanev** [comment]
When I tried to download the file from "https://yt-dl.org/downloads/2020.01.15/youtube-dl" I got a lot smaller file then the old one. (new 1.7 MB, old 7.84 MB) I had to put the extensions myself and after the change, the app doesn't want to download at all. (stays at 0 downloaded) Did I do something wrong or I haven't read everything necessary?

**Comment by ReachForTheDead** [comment]
> 
> 
> When I tried to download the file from "https://yt-dl.org/downloads/2020.01.15/youtube-dl" I got a lot smaller file then the old one. (new 1.7 MB, old 7.84 MB) I had to put the extensions myself and after the change, the app doesn't want to download at all. (stays at 0 downloaded) Did I do something wrong or I haven't read everything necessary?

It was stuck for me too; just left the PC downloading it and after some hours I got it working.

**Comment by alvaro-canepa** [comment]
The same problem from Spotify, from Linux Mint.
Here is my log.
```bash
{ name: 'saving-path',
  value: '/home/alvaro/Música/Spotify',
  _id: 'SgeNNGUEFH0xcNFr' }
[DB] findOne { db: 'config', query: { name: 'saving-path' } }
{ name: 'saving-path',
  value: '/home/alvaro/Música/Spotify',
  _id: 'SgeNNGUEFH0xcNFr' }
[DB] findOne { db: 'config', query: { name: 'help-displayedn' } }
{ name: 'help-displayedn', value: 2, _id: 'RoKf3GQx24pmorVC' }
[AT3] suggestions https://open.spotify.com/playlist/37i9dQZF1DX1kydukZhLms?si=W-LK3NvETFG-irxqOfaYyw
[AT3] downloadPlaylist { folder: '/home/alvaro/Música/Spotify/',
  id: 'cQ2K21IY9g',
  url: 'https://open.spotify.com/playlist/37i9dQZF1DX1kydukZhLms?si=W-LK3NvETFG-irxqOfaYyw' }
[AT3] event begin-url 0
[AT3] event begin-url 1
[AT3] event begin-url 2
[AT3] event begin-url 3
[AT3] event error Error: 3
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 1
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 0
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 2
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by StephaneColson** [comment]
Same problem on MacOS. Log:

```
[AT3] event error Error: 0
    at at3.findVideoForSong.then.catch (/Users/stephane/Code/alltomp3-app/node_modules/alltomp3/index.js:2086:29)
    at tryCatcher (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/stephane/Code/alltomp3-app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by tracker2010** [comment]
> It's always been a little hit and miss, but I can't get anything to download now.
> Update - Just got it working by following this from another post:
> 
> 1. Download the .exe from here: https://yt-dl.org/downloads/2020.01.15/youtube-dl
> 2. Overwrite the 'youtube-dl.exe in here: :\Users<YOURLOGINID>\AppData\Local\Programs\AllToMP3\resources\app.asar.unpacked\node_modules\youtube-dl\bin
> 
> Double update: It's now back to being 'a bit hit and miss' where it'll only download a few songs before 'seizing up'.

just wondering how to unpack the files since i am a major noob

**Comment by MrGKanev** [comment]
@tracker2010 which files? The link provided should give you only a "youtube-dl" file without even an extension. You need to replace it directly with the file and everything should work. When I tried it I wasn't really successful but I had changed OS-ses so that may be the problem.

**Comment by AmazingGabriel16** [comment]
So this is still dead for windows?

OOF!

**Comment by codereveryday** [comment]
spotdl is a great alt https://github.com/spotDL/spotify-downloader
