### ISSUE TITLE
Your app is ideal format/style wise but it won't download from any source :/

### ISSUE THREAD

**Issue by egg98** [AllToMP3/alltomp3-app#157]
<!--
 My operating system is:  Mac OS Mojave - version 10.14.4
My AllToMP3 version is: Version 0.3.12 

I know you asked for a specific URL but the problem is unfortunately with all URL. (Youtube or Spotify - songs,albums, playlists) 

For example, if i try to download an album (eg https://open.spotify.com/album/4TkmrrpjlPoCPpGyDN3rkF?si=cDMlUxyiRZ-Epds-dkUetg):

The album name will download to my desktop BUT NOT THE SONGS. It will download initial information (album artist, then album name) but not the songs.  I've waited hours for several different songs but it won't load :( 

<img width="804" alt="Screen Shot 2020-04-11 at 4 01 06 PM" src="https://user-images.githubusercontent.com/34256057/79053771-ba493380-7c0d-11ea-9ad6-64af4fee929d.png">
<img width="794" alt="Screen Shot 2020-04-11 at 4 01 01 PM" src="https://user-images.githubusercontent.com/34256057/79053773-bae1ca00-7c0d-11ea-9425-1b6d21158d48.png">
<img width="790" alt="Screen Shot 2020-04-11 at 4 00 56 PM" src="https://user-images.githubusercontent.com/34256057/79053774-bae1ca00-7c0d-11ea-9724-c2c7631ec680.png">
<img width="520" alt="Screen Shot 2020-04-11 at 3 59 57 PM" src="https://user-images.githubusercontent.com/34256057/79053775-bae1ca00-7c0d-11ea-9a7c-916616799865.png">

**Comment by AnimalFriend1** [comment]
The same thing is happening on Windows 10...

**Comment by vrigolon** [comment]
Same on Linux.
OS: Manjaro 20.0
Alltomp3: 0.3.12.59-2

**Comment by roenw** [comment]
Happening on Win10. Unable to download any songs

**Comment by thomastrinn** [comment]
Hi!

Sadly I get the same problem. 

OS: Ubuntu 18.04

For youtube:
`
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/opt/AllToMP3/resources/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1385, in _decrypt_signature
    video_id, player_url, s
  File "/opt/AllToMP3/resources/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/s/player/0374edcb/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/s/player/0374edcb/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

For spotify.
`
[AT3] event error Error: 2
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 0
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 1
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[AT3] event error Error: 3
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2222:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

I hope this helps to find the reason.

**Comment by Winichskorn** [comment]
Same problem on Mac 10.15 trying to download a Spotify playlist :/
It seems this issue has been going on for at least a few months now, probably because Spotify patched it.

**Comment by AmazingGabriel16** [comment]
Please try this: https://github.com/AllToMP3/alltomp3-app/issues/160

**Comment by vrigolon** [comment]
Its fixed!!!!!
The new version 0.3.17 is working on Linux Manjaro. 
Thanks to the Devs.
