### ISSUE TITLE
Still no Spotify downloads

### ISSUE THREAD

**Issue by Codingboy65** [AllToMP3/alltomp3-app#161]
I was wondering if there is progress being put into making the program able to download from Spotify

**Comment by daansteegmans** [comment]
same here..

**Comment by Auranna07** [comment]
Same! I tried to do the trick of the youtube dl...but this time didn't worked...

**Comment by NTag** [comment]
The latest update of AllToMP3 (0.3.14) should fix YouTube downloads; but Spotify or downloads from song title are still broken, I'm trying to figure out a solution.

**Comment by daansteegmans** [comment]
Thanks man!

**Comment by Codingboy65** [comment]
You are a saver

**Comment by Auranna07** [comment]
Thanks a lot!

**Comment by Andrea5883** [comment]
Thanks for this great tool. Would also like to know once the Spotify downloads are working again.

**Comment by 616659** [comment]
I'm also really hoping for Spotify issue to be fixed again soon. Keep up the great work!

**Comment by daansteegmans** [comment]
Same here, Spotify would be so nice again. Bonne chance & Keep it up!

**Comment by HeSoKa05** [comment]
@NTag 
I installed Alltomp3 on ubuntu 18.04 and on Windows 10, I have the same problem for a while.
Today I launch it on ubuntu via Terminal, it runs normally and shows some info. When I press enter after past the URL, this is what I get in terminal:

`Unhandled rejection TypeError: Cannot set property 'progress' of undefined
    at downloadNext (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2119:27)
    at at3.getPlaylistTitlesInfos.then (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2097:7)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
[AT3] event error Error: 0
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2212:31)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
Unhandled rejection TypeError: Cannot set property 'progress' of undefined
    at downloadNext (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2119:27)
    at at3.findVideoForSong.then.catch (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2214:11)
    at tryCatcher (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/AllToMP3/resources/app/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)`

I tried to reinstall it during Terminal, it installed successfully, but during installation, it shows this msg:

`chmod: cannot access '/opt/AllToMP3/chrome-sandbox': No such file or directory`

Is this problem only on my Ubuntu system or it's a general problem? does it have any effects on the program? I mean is this what causes the problem of downloading songs?  if yes, how can I solve it?


I think this will help you to find the bug easily.
thank you.

**Comment by NTag** [comment]
Can you try again Spotify with the latest update (0.3.17)? As well as the search by name.

**Comment by Mykros** [comment]
Works like a charm, be it name search or spotify URL (cretaed a github account just to give you kudos, discovered your app today :D)

**Comment by Codingboy65** [comment]
Very good, works wonderfully

**Comment by nerohunter9** [comment]
@NTag it's not working for some reason been trying to figure it out for a couple of hours. can you help me out?
