### ISSUE TITLE
Can't install on Kubuntu 20.04

### ISSUE THREAD

**Issue by webmadmangit** [AllToMP3/alltomp3-app#209]
* My operating system is: Kubuntu 20.04 (focal);
* My AllToMP3 version is: none yet;

The script installed the repo without issue, but when i tried to refresh apt I got this error-
"The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu focal Release' does not have a Release file."

And it won't download from it, so no alltomp3 to install.

**Comment by satyendrachaudhary** [comment]
Same here. Adding few logs that might help.
`
error /home/USER/Desktop/alltomp3-app/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/USER/Desktop/alltomp3-app/node_modules/sharp
Output:
info sharp Using cached /root/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.19.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/snap/node/3292/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/USER/Desktop/alltomp3-app/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/snap/node/3292/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/snap/node/3292/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/USER/Desktop/alltomp3-app/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/USER/Desktop/alltomp3-app/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:27:
../src/common.h:82:20: error: ‘Handle’ is not a member of ‘v8’
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                    ^~~~~~
../src/common.h:82:37: error: expected primary-expression before ‘>’ token
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                     ^
../src/common.h:82:39: error: ‘obj’ was not declared in this scope
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                       ^~~
../src/common.h:82:56: error: expected primary-expression before ‘attr’
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                        ^~~~
../src/common.h:82:60: error: expression list treated as compound expression in initializer [-fpermissive]
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                            ^
../src/common.h:83:29: error: ‘Handle’ is not a member of ‘v8’
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                             ^~~~~~
../src/common.h:83:46: error: expected primary-expression before ‘>’ token
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                              ^
../src/common.h:83:48: error: ‘obj’ was not declared in this scope
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                ^~~
../src/common.h:83:65: error: expected primary-expression before ‘attr’
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |                                                                 ^~~~
../src/common.h:84:48: error: ‘Handle’ is not a member of ‘v8’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                ^~~~~~
../src/common.h:84:65: error: expected primary-expression before ‘>’ token
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                 ^
../src/common.h:84:67: error: ‘obj’ was not declared in this scope
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                   ^~~
../src/common.h:84:84: error: expected primary-expression before ‘attr’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                                    ^~~~
../src/common.h:84:37: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^~~~~~
../src/common.h:84:89: error: expected ‘;’ before ‘{’ token
   84 |   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                                         ^~
      |                                                                                         ;
../src/common.h:87:37: error: ‘Handle’ is not a member of ‘v8’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^~~~~~
../src/common.h:87:54: error: expected primary-expression before ‘>’ token
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                      ^
../src/common.h:87:56: error: ‘obj’ was not declared in this scope
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                        ^~~
../src/common.h:87:73: error: expected primary-expression before ‘attr’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                         ^~~~
../src/common.h:87:26: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                          ^~~~~~
../src/common.h:87:78: error: expected ‘;’ before ‘{’ token
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                              ^~
      |                                                                              ;
../src/common.h:90:37: error: ‘Handle’ is not a member of ‘v8’
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                     ^~~~~~
../src/common.h:90:54: error: expected primary-expression before ‘>’ token
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                      ^
../src/common.h:90:56: error: ‘obj’ was not declared in this scope
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                        ^~~
../src/common.h:90:61: error: expected primary-expression before ‘int’
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                             ^~~
../src/common.h:87:26: warning: variable templates only available with ‘-std=c++14’ or ‘-std=gnu++14’
   87 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
      |                          ^~~~~~
../src/common.h:90:70: error: expected ‘;’ before ‘{’ token
   90 |   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
      |                                                                      ^~
      |                                                                      ;
../src/common.h:96:9: error: ‘Handle’ is not a member of ‘v8’
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |         ^~~~~~
../src/common.h:96:26: error: expected primary-expression before ‘>’ token
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                          ^
../src/common.h:96:28: error: ‘input’ was not declared in this scope
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                            ^~~~~
../src/common.h:96:70: error: expected primary-expression before ‘&’ token
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                      ^
../src/common.h:96:71: error: ‘buffersToPersist’ was not declared in this scope
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                       ^~~~~~~~~~~~~~~~
../src/common.h:96:87: error: expression list treated as compound expression in initializer [-fpermissive]
   96 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
      |                                                                                       ^
../src/common.cc:34:8: error: redefinition of ‘bool sharp::HasAttr’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |        ^~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:82:8: note: ‘bool sharp::HasAttr’ previously defined here
   82 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
      |        ^~~~~~~
../src/common.cc:34:20: error: ‘Handle’ is not a member of ‘v8’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                    ^~~~~~
../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                     ^
../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                       ^~~
../src/common.cc:34:56: error: expected primary-expression before ‘attr’
   34 |   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                        ^~~~
../src/common.cc:37:15: error: redefinition of ‘std::string sharp::AttrAsStr’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |               ^~~~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:83:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
   83 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
      |               ^~~~~~~~~
../src/common.cc:37:29: error: ‘Handle’ is not a member of ‘v8’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                             ^~~~~~
../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                              ^
../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                ^~~
../src/common.cc:37:65: error: expected primary-expression before ‘attr’
   37 |   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
      |                                                                 ^~~~
../src/common.cc:42:20: error: redefinition of ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’
   42 |   InputDescriptor* CreateInputDescriptor(
      |                    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/common.cc:27:
../src/common.h:95:20: note: ‘sharp::InputDescriptor* sharp::CreateInputDescriptor’ previously defined here
   95 |   InputDescriptor* CreateInputDescriptor(
      |                    ^~~~~~~~~~~~~~~~~~~~~
../src/common.cc:43:9: error: ‘Handle’ is not a member of ‘v8’
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |         ^~~~~~
../src/common.cc:43:26: error: expected primary-expression before ‘>’ token
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                          ^
../src/common.cc:43:28: error: ‘input’ was not declared in this scope
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                            ^~~~~
../src/common.cc:43:70: error: expected primary-expression before ‘&’ token
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                                                                      ^
../src/common.cc:43:71: error: ‘buffersToPersist’ was not declared in this scope
   43 |     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist
      |                                                                       ^~~~~~~~~~~~~~~~
make: *** [sharp.target.mk:136: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/USER/Desktop/alltomp3-app/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/snap/node/3292/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.8.0-50-generic
gyp ERR! command "/snap/node/3292/bin/node" "/snap/node/3292/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/USER/Desktop/alltomp3-app/node_modules/sharp
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
`
