### ISSUE TITLE
JavaScript error 

### ISSUE THREAD

**Issue by Reaghaar** [AllToMP3/alltomp3-app#25]
After the new release that the installation error was fixed in Linux Mint 18.3 Sylvia, I tried to start the program and I was surprised with a misfortune of one more error, a JavaScript error. My question is, the error is a flaw in the program or in my operation system?
Here is the error:

wagner@wagner-H14CU01 ~ $ sudo apt-get install alltomp3
[sudo] senha para wagner: 
Sinto muito, tente novamente.
[sudo] senha para wagner: 
Sinto muito, tente novamente.
[sudo] senha para wagner: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Os NOVOS pacotes a seguir serão instalados:
  alltomp3
0 pacotes atualizados, 1 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
É preciso baixar 0 B/51,4 MB de arquivos.
Depois desta operação, 217 MB adicionais de espaço em disco serão usados.
A seleccionar pacote anteriormente não seleccionado alltomp3.
(Lendo banco de dados ... 251537 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../alltomp3_0.3.3_amd64.deb ...
A descompactar alltomp3 (0.3.3) ...
A processar 'triggers' para gnome-menus (3.13.3-6ubuntu3.1) ...
A processar 'triggers' para desktop-file-utils (0.22+linuxmint1) ...
A processar 'triggers' para mime-support (3.59ubuntu1) ...
A processar 'triggers' para hicolor-icon-theme (0.15-0ubuntu1) ...
Configurando alltomp3 (0.3.3) ...
wagner@wagner-H14CU01 ~ $ alltomp3
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/AllToMP3/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/constructor.js:10:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/constructor.js:253:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/index.js:15:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:17:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2261:3)
Falha de segmentação (imagem do núcleo gravada)
wagner@wagner-H14CU01 ~ $

**Comment by rubendbg** [comment]
Same issue for me!

**Comment by coolaspie** [comment]
Yeah I also have the same issue

**Comment by nemyxa** [comment]
Same shit, will it be fixed?

**Comment by ih8myself** [comment]
Following steps solved my problem:

[Download](https://sourceforge.net/projects/libpng/files/zlib/1.2.9/zlib-1.2.9.tar.gz/download) zlib version 1.2.9
Uncompress the file
cd to zlib-1.2.9
Run
./configure; make; make install
libz.so.1.2.9 is installed under /usr/local/lib
cd to /lib/x86_64-linux-gnu
Give the link
ln -s -f /usr/local/lib/libz.so.1.2.9/lib libz.so.1

**Comment by coolaspie** [comment]
@ih8myself Thank you. That fixes it for me

**Comment by ih8myself** [comment]
Now i got other issue...

`[AT3] suggestions https://open.spotify.com/user/XXXXXXXX
[AT3] downloadPlaylist { folder: '/xxxx/',
  id: 'QIPaya6mXY',
  url: 'https://open.spotify.com/user/xxxxxxxx'' }
[AT3] event begin-url 0
Unhandled rejection StatusCodeError: 400 - [object Object]
    at new StatusCodeError (/opt/AllToMP3/resources/app/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/opt/AllToMP3/resources/app/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/opt/AllToMP3/resources/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/opt/AllToMP3/resources/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/opt/AllToMP3/resources/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

the exes are for local folders and spotify playlist

**Comment by Reaghaar** [comment]
@ih8myself worked here, thanks for your help man.

**Comment by nemyxa** [comment]
@ih8myself awesome, bro

**Comment by VandiumRoadrunner** [comment]
This solution does not work for me. When I create the link it freezes my computer completely and I have to can only fix the problem with a system backup file I have on the computer. I suspect this is because I have a lib conflict. Under **/lib/x86_64-linux-gnu** I have files as **libz.so.1** and **libz.so.1.2.8**. Could someone guide me as to what might the conflict be? Many thanks.

**Comment by ih8myself** [comment]
That is because zlib version was registered on the kernel's method to apply the library when required.

**Comment by iSweetHero** [comment]
Hello, i have the same error, the ih8myself commands crashed the pc, because on ubuntu the folder /usr/local/lib don't have the libs, this folder is for python.
To fix change the commands to

./configure; make; make install libz.so.1.2.9 is installed under /usr/lib

ln -s -f /usr/lib/libz.so.1.2.9/lib libz.so.1

**Comment by ramaralo** [comment]
> Following steps solved my problem:
> 
> [Download](https://sourceforge.net/projects/libpng/files/zlib/1.2.9/zlib-1.2.9.tar.gz/download) zlib version 1.2.9
> Uncompress the file
> cd to zlib-1.2.9
> Run
> ./configure; make; make install
> libz.so.1.2.9 is installed under /usr/local/lib
> cd to /lib/x86_64-linux-gnu
> Give the link
> ln -s -f /usr/local/lib/libz.so.1.2.9/lib libz.so.1

^^^ This worked for me. Thanks!
Ubuntu 16.04
