### ISSUE TITLE
ZLIB_1.2.9 not found

### ISSUE THREAD

**Issue by senchastic** [AllToMP3/alltomp3-app#27]
any suggestions? i'm running mint 18.3 /w kde

> barti@vmware ~ $ alltomp3 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/constructor.js:10:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/constructor.js:255:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/index.js:15:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:17:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2254:3)
Segmentation fault (core dumped)
barti@vmware ~ $

**Comment by melyamri** [comment]
I had the same issue, as mentioned in [this comment](https://github.com/AllToMP3/alltomp3-app/issues/25#issuecomment-371582608), downloading and installing zlib 1.2.9 solved my problem.

You can download [zlib version 1.2.9](https://sourceforge.net/projects/libpng/?source=typ_redirect) and uncompress it.

```
cd zlib-1.2.9
./configure
make
make install
```
I'm running Ubuntu 16.04, and the the symbolic link was automatically created, but maybe in your case you should do that to.

**Comment by vushe** [comment]
@melyamri's fix is working, however, zlib v. 1.2.9 should be mentioned as a requirement or so. I confirm issue existing on Linux Mint 18.3 (i.e. Ubuntu 16.04 based).
