### ISSUE TITLE
Segfault at first run from Linux Mint 17.3

### ISSUE THREAD

**Issue by fralix** [AllToMP3/alltomp3-app#4]
fralix@lm17-3 ~ $ alltomp3 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/AllToMP3/resources/app/node_modules/sharp/build/Release/sharp.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/constructor.js:8:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/constructor.js:233:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/sharp/lib/index.js:19:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
Segmentation fault
fralix@lm17-3 ~ $

**Comment by ArthurAssuncao** [comment]
Try install:
```
apt-get install libstdc++6
```

**Comment by fralix** [comment]
```
fralix@lm17-3 ~ $ sudo apt-get install libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
fralix@lm17-3 ~ $ 
```
(missing upgrade is `wammu`)

**Comment by NTag** [comment]
Maybe this thread could help https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx?

**Comment by fralix** [comment]
Oh thanks, App is opening now. I try it now.
