### ISSUE TITLE
Linux app not working

### ISSUE THREAD

**Issue by harshitdiit** [AllToMP3/alltomp3-app#77]
### Log  

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libz.so.1: version 'ZLIB_1.2.9' not found (required by /opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/constructor.js:10:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/constructor.js:255:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/node_modules/sharp/lib/index.js:15:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:17:15)
    at Object.<anonymous> (/opt/AllToMP3/resources/app/node_modules/alltomp3/index.js:2254:3)`

Segmentation fault (core dumped)

**Comment by harshitdiit** [comment]
It can be fixed by explicitly installing ZLIB_1.2.9 
[Download](https://sourceforge.net/projects/libpng/files/zlib/1.2.9/zlib-1.2.9.tar.gz/download) from here.
Extract and cd into the extracted folder.
Open a terminal in this location, and successively run
`./configure`
`make`
`sudo make install`
`cd /lib/x86_64-linux-gnu`
`sudo ln -s -f /usr/local/lib/libz.so.1.2.9/lib libz.so.1`
If firefox misbehaves after this, run
`sudo ln -s -f /lib/x86_64-linux-gnu/libz.so.1.2.8 /lib/x86_64-linux-gnu/libz.so.1`

Cheers!
