### ISSUE TITLE
Download progress circle stops at bottom

### ISSUE THREAD

**Issue by fralix** [AllToMP3/alltomp3-app#8]
Trying to download any song from any tested service (tested Youtube, Spotify, the note and disc icon in search) shows the song but the download animation stops at the bottom. (50%)
I got some folder architecture but the files weren't stored in there.

**Comment by fralix** [comment]
caught this from terminal:
```
{ name: 'saving-path',
  value: '/home/fralix/Musik',
  _id: 'p797B66t0JhM2DcU' }
[DB] findOne { db: 'config', query: { name: 'saving-path' } }
{ name: 'saving-path',
  value: '/home/fralix/Musik',
  _id: 'p797B66t0JhM2DcU' }
[DB] findOne { db: 'config', query: { name: 'help-displayedn' } }
{ name: 'help-displayedn', value: 2, _id: 'DnRXqTJYtO5zB6kp' }
[AT3] suggestions libmp3lame
[AT3] suggestions lorde - green light
[AT3] downloadTrack { folder: '/home/fralix/Musik/',
  id: 'zm0X6UVWAQ',
  track: 
   { artistName: 'Lorde',
     cover: 'https://e-cdns-images.dzcdn.net/images/cover/5d02bd5b125a3c0fb4f8a6f85c65f802/250x250-000000-80-0-0.jpg',
     deezerId: 371625771,
     duration: 234,
     title: 'Green Light' } }
[AT3] event download { progress: '0.43' }
[AT3] event download { progress: '0.86' }
[AT3] event download { progress: '1.30' }
[AT3] event download { progress: '1.73' }
...
[AT3] event download { progress: '99.31' }
[AT3] event download { progress: '99.74' }
[AT3] event download { progress: '100.00' }
[AT3] event download-end undefined
Error: Audio codec libmp3lame is not available
    at /opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/capabilities.js:638:21
    at nextTask (/opt/AllToMP3/resources/app/node_modules/async/dist/async.js:5273:14)
    at next (/opt/AllToMP3/resources/app/node_modules/async/dist/async.js:5280:9)
    at /opt/AllToMP3/resources/app/node_modules/async/dist/async.js:906:16
    at /opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/capabilities.js:484:7
    at handleExit (/opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/processor.js:165:11)
    at Socket.<anonymous> (/opt/AllToMP3/resources/app/node_modules/fluent-ffmpeg/lib/processor.js:192:11)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

```

**Comment by NTag** [comment]
You might be missing some packages for ffmpeg to support mp3. Which distribution are you on?

On my Debian, I installed `libmp3lame0` and `libavcodec56` (but the names can be slightly different depending on your distrib).

**Comment by fralix** [comment]
I'm on Linux Mint 17.3 (Ubuntu 14.04) and installing latest updates to these packages didn't solve anything. I'll try to fetch newer versions.

**Comment by fralix** [comment]
Okay
https://superuser.com/questions/831473/unknown-encoder-libmp3lame-in-ubuntu-14-04
was very useful. I added the PPA and installed the new ffmpeg.

**Comment by NTag** [comment]
Great 🙂 ! I added a message regarding old distributions on Linux installation instructions on the website.

**Comment by fralix** [comment]
You might want to provide more details like this PPA https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media to solve the problem.
